### ISSUE TITLE
配置单个config报错

### ISSUE THREAD

**Issue by hxu-aa** [mitnk/kofconfig#1]
如果电脑没有外置键盘（不足两个键盘的情况），配置一个一会报错。
命令：kofconfig -p1 JKLIZXVC
结果：

Traceback (most recent call last):
  File "/usr/local/bin/kofconfig", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/kofconfig.py", line 197, in main
    config(keys_p1=p1, keys_p2=p2)
  File "/usr/local/lib/python2.7/site-packages/kofconfig.py", line 167, in config
    mulit_kbd = is_using_multiple_keyboard()
  File "/usr/local/lib/python2.7/site-packages/kofconfig.py", line 69, in is_using_multiple_keyboard
    ['grep', '-i', 'keyboard'], stdin=usb_info.stdout)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['grep', '-i', 'keyboard']' returned non-zero exit status 1

**Comment by mitnk** [comment]
fixed ;)
